-- Auto-generated by generate_tamper_triggers.py
-- DO NOT EDIT — regenerate with: python3 sql/generate_tamper_triggers.py

USE olympia_auth;

CREATE TABLE IF NOT EXISTS direct_modification_log (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    detected_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    db_user      VARCHAR(100) NOT NULL,
    table_name   VARCHAR(50)  NOT NULL,
    operation    ENUM('INSERT','UPDATE','DELETE') NOT NULL,
    row_key      VARCHAR(255),
    details      TEXT
);

GRANT INSERT ON olympia_auth.direct_modification_log TO 'olympia_app'@'localhost';
GRANT SELECT ON olympia_auth.direct_modification_log TO 'olympia_app'@'localhost';

DELIMITER //

DROP TRIGGER IF EXISTS olympia_track.Member_direct_insert//

CREATE TRIGGER olympia_track.Member_direct_insert
BEFORE INSERT ON olympia_track.Member
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.MemberID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Member', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'Member', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'Member', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Member_direct_update//

CREATE TRIGGER olympia_track.Member_direct_update
BEFORE UPDATE ON olympia_track.Member
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.MemberID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Member', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'Member', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'Member', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Member_direct_delete//

CREATE TRIGGER olympia_track.Member_direct_delete
BEFORE DELETE ON olympia_track.Member
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.MemberID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Member', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'Member', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'Member', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Sport_direct_insert//

CREATE TRIGGER olympia_track.Sport_direct_insert
BEFORE INSERT ON olympia_track.Sport
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.SportID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Sport', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'Sport', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'Sport', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Sport_direct_update//

CREATE TRIGGER olympia_track.Sport_direct_update
BEFORE UPDATE ON olympia_track.Sport
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.SportID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Sport', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'Sport', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'Sport', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Sport_direct_delete//

CREATE TRIGGER olympia_track.Sport_direct_delete
BEFORE DELETE ON olympia_track.Sport
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.SportID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Sport', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'Sport', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'Sport', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Venue_direct_insert//

CREATE TRIGGER olympia_track.Venue_direct_insert
BEFORE INSERT ON olympia_track.Venue
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.VenueID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Venue', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'Venue', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'Venue', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Venue_direct_update//

CREATE TRIGGER olympia_track.Venue_direct_update
BEFORE UPDATE ON olympia_track.Venue
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.VenueID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Venue', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'Venue', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'Venue', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Venue_direct_delete//

CREATE TRIGGER olympia_track.Venue_direct_delete
BEFORE DELETE ON olympia_track.Venue
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.VenueID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Venue', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'Venue', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'Venue', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Tournament_direct_insert//

CREATE TRIGGER olympia_track.Tournament_direct_insert
BEFORE INSERT ON olympia_track.Tournament
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.TournamentID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Tournament', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'Tournament', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'Tournament', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Tournament_direct_update//

CREATE TRIGGER olympia_track.Tournament_direct_update
BEFORE UPDATE ON olympia_track.Tournament
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.TournamentID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Tournament', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'Tournament', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'Tournament', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Tournament_direct_delete//

CREATE TRIGGER olympia_track.Tournament_direct_delete
BEFORE DELETE ON olympia_track.Tournament
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.TournamentID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Tournament', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'Tournament', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'Tournament', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Team_direct_insert//

CREATE TRIGGER olympia_track.Team_direct_insert
BEFORE INSERT ON olympia_track.Team
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.TeamID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Team', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'Team', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'Team', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Team_direct_update//

CREATE TRIGGER olympia_track.Team_direct_update
BEFORE UPDATE ON olympia_track.Team
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.TeamID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Team', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'Team', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'Team', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Team_direct_delete//

CREATE TRIGGER olympia_track.Team_direct_delete
BEFORE DELETE ON olympia_track.Team
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.TeamID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Team', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'Team', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'Team', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.TeamMember_direct_insert//

CREATE TRIGGER olympia_track.TeamMember_direct_insert
BEFORE INSERT ON olympia_track.TeamMember
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(CONCAT(NEW.TeamID, ',', NEW.MemberID) AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'TeamMember', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'TeamMember', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'TeamMember', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.TeamMember_direct_update//

CREATE TRIGGER olympia_track.TeamMember_direct_update
BEFORE UPDATE ON olympia_track.TeamMember
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(CONCAT(OLD.TeamID, ',', OLD.MemberID) AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'TeamMember', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'TeamMember', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'TeamMember', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.TeamMember_direct_delete//

CREATE TRIGGER olympia_track.TeamMember_direct_delete
BEFORE DELETE ON olympia_track.TeamMember
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(CONCAT(OLD.TeamID, ',', OLD.MemberID) AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'TeamMember', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'TeamMember', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'TeamMember', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Event_direct_insert//

CREATE TRIGGER olympia_track.Event_direct_insert
BEFORE INSERT ON olympia_track.Event
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.EventID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Event', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'Event', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'Event', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Event_direct_update//

CREATE TRIGGER olympia_track.Event_direct_update
BEFORE UPDATE ON olympia_track.Event
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.EventID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Event', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'Event', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'Event', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Event_direct_delete//

CREATE TRIGGER olympia_track.Event_direct_delete
BEFORE DELETE ON olympia_track.Event
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.EventID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Event', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'Event', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'Event', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Participation_direct_insert//

CREATE TRIGGER olympia_track.Participation_direct_insert
BEFORE INSERT ON olympia_track.Participation
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.ParticipationID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Participation', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'Participation', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'Participation', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Participation_direct_update//

CREATE TRIGGER olympia_track.Participation_direct_update
BEFORE UPDATE ON olympia_track.Participation
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.ParticipationID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Participation', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'Participation', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'Participation', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Participation_direct_delete//

CREATE TRIGGER olympia_track.Participation_direct_delete
BEFORE DELETE ON olympia_track.Participation
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.ParticipationID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Participation', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'Participation', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'Participation', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Equipment_direct_insert//

CREATE TRIGGER olympia_track.Equipment_direct_insert
BEFORE INSERT ON olympia_track.Equipment
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.EquipmentID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Equipment', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'Equipment', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'Equipment', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Equipment_direct_update//

CREATE TRIGGER olympia_track.Equipment_direct_update
BEFORE UPDATE ON olympia_track.Equipment
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.EquipmentID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Equipment', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'Equipment', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'Equipment', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.Equipment_direct_delete//

CREATE TRIGGER olympia_track.Equipment_direct_delete
BEFORE DELETE ON olympia_track.Equipment
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.EquipmentID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'Equipment', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'Equipment', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'Equipment', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.EquipmentIssue_direct_insert//

CREATE TRIGGER olympia_track.EquipmentIssue_direct_insert
BEFORE INSERT ON olympia_track.EquipmentIssue
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.IssueID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'EquipmentIssue', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'EquipmentIssue', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'EquipmentIssue', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.EquipmentIssue_direct_update//

CREATE TRIGGER olympia_track.EquipmentIssue_direct_update
BEFORE UPDATE ON olympia_track.EquipmentIssue
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.IssueID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'EquipmentIssue', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'EquipmentIssue', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'EquipmentIssue', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.EquipmentIssue_direct_delete//

CREATE TRIGGER olympia_track.EquipmentIssue_direct_delete
BEFORE DELETE ON olympia_track.EquipmentIssue
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.IssueID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'EquipmentIssue', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'EquipmentIssue', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'EquipmentIssue', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.PracticeSession_direct_insert//

CREATE TRIGGER olympia_track.PracticeSession_direct_insert
BEFORE INSERT ON olympia_track.PracticeSession
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.SessionID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'PracticeSession', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'PracticeSession', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'PracticeSession', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.PracticeSession_direct_update//

CREATE TRIGGER olympia_track.PracticeSession_direct_update
BEFORE UPDATE ON olympia_track.PracticeSession
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.SessionID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'PracticeSession', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'PracticeSession', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'PracticeSession', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.PracticeSession_direct_delete//

CREATE TRIGGER olympia_track.PracticeSession_direct_delete
BEFORE DELETE ON olympia_track.PracticeSession
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.SessionID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'PracticeSession', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'PracticeSession', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'PracticeSession', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.PerformanceLog_direct_insert//

CREATE TRIGGER olympia_track.PerformanceLog_direct_insert
BEFORE INSERT ON olympia_track.PerformanceLog
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.LogID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'PerformanceLog', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'PerformanceLog', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'PerformanceLog', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.PerformanceLog_direct_update//

CREATE TRIGGER olympia_track.PerformanceLog_direct_update
BEFORE UPDATE ON olympia_track.PerformanceLog
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.LogID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'PerformanceLog', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'PerformanceLog', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'PerformanceLog', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.PerformanceLog_direct_delete//

CREATE TRIGGER olympia_track.PerformanceLog_direct_delete
BEFORE DELETE ON olympia_track.PerformanceLog
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.LogID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'PerformanceLog', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'PerformanceLog', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'PerformanceLog', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.MedicalRecord_direct_insert//

CREATE TRIGGER olympia_track.MedicalRecord_direct_insert
BEFORE INSERT ON olympia_track.MedicalRecord
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(NEW.RecordID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'MedicalRecord', 'INSERT', _record_id, 'INSERT detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'INSERT', '|',
            'MedicalRecord', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'INSERT', 'MedicalRecord', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.MedicalRecord_direct_update//

CREATE TRIGGER olympia_track.MedicalRecord_direct_update
BEFORE UPDATE ON olympia_track.MedicalRecord
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.RecordID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'MedicalRecord', 'UPDATE', _record_id, 'UPDATE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'UPDATE', '|',
            'MedicalRecord', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'UPDATE', 'MedicalRecord', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DROP TRIGGER IF EXISTS olympia_track.MedicalRecord_direct_delete//

CREATE TRIGGER olympia_track.MedicalRecord_direct_delete
BEFORE DELETE ON olympia_track.MedicalRecord
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '7289d4d3b76b1fc8690a009ee214f37e5c7fc6e08cce989876a6e1249108dfd4' THEN
        SET _record_id = CAST(OLD.RecordID AS CHAR);
        SET _details = CONCAT('{"source":"direct_db","db_user":"', CURRENT_USER(), '"}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), 'MedicalRecord', 'DELETE', _record_id, 'DELETE detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            'DELETE', '|',
            'MedicalRecord', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', 'DELETE', 'MedicalRecord', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//

DELIMITER ;
