#!/usr/bin/env python3
"""
Reads API_CONTEXT_SECRET from .env and generates sql/06_tamper_detection.sql
with the secret baked into every trigger definition as a string literal.

Triggers log unauthorized direct DB modifications to BOTH:
  - olympia_auth.direct_modification_log  (dedicated tamper table)
  - olympia_auth.audit_log                (main audit log with hash chain)
"""
import os
import sys

from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env"))

secret = os.getenv("API_CONTEXT_SECRET")
if not secret:
    print("ERROR: API_CONTEXT_SECRET not set in .env", file=sys.stderr)
    sys.exit(1)

# (table_name, pk_expression for NEW row, pk_expression for OLD row)
# For composite PKs we CONCAT them.
TABLES = [
    ("Member",          "NEW.MemberID",          "OLD.MemberID"),
    ("Sport",           "NEW.SportID",           "OLD.SportID"),
    ("Venue",           "NEW.VenueID",           "OLD.VenueID"),
    ("Tournament",      "NEW.TournamentID",      "OLD.TournamentID"),
    ("Team",            "NEW.TeamID",            "OLD.TeamID"),
    ("TeamMember",      "CONCAT(NEW.TeamID, ',', NEW.MemberID)",
                        "CONCAT(OLD.TeamID, ',', OLD.MemberID)"),
    ("Event",           "NEW.EventID",           "OLD.EventID"),
    ("Participation",   "NEW.ParticipationID",   "OLD.ParticipationID"),
    ("Equipment",       "NEW.EquipmentID",       "OLD.EquipmentID"),
    ("EquipmentIssue",  "NEW.IssueID",           "OLD.IssueID"),
    ("PracticeSession", "NEW.SessionID",         "OLD.SessionID"),
    ("PerformanceLog",  "NEW.LogID",             "OLD.LogID"),
    ("MedicalRecord",   "NEW.RecordID",          "OLD.RecordID"),
]

OPS = [
    ("INSERT", "BEFORE INSERT", "new_pk"),
    ("UPDATE", "BEFORE UPDATE", "old_pk"),
    ("DELETE", "BEFORE DELETE", "old_pk"),
]

out_path = os.path.join(os.path.dirname(__file__), "06_tamper_detection.sql")

lines = []
lines.append("-- Auto-generated by generate_tamper_triggers.py")
lines.append("-- DO NOT EDIT — regenerate with: python3 sql/generate_tamper_triggers.py\n")

lines.append("USE olympia_auth;\n")

# Log table
lines.append("""CREATE TABLE IF NOT EXISTS direct_modification_log (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    detected_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    db_user      VARCHAR(100) NOT NULL,
    table_name   VARCHAR(50)  NOT NULL,
    operation    ENUM('INSERT','UPDATE','DELETE') NOT NULL,
    row_key      VARCHAR(255),
    details      TEXT
);
""")

# Grants
lines.append("GRANT INSERT ON olympia_auth.direct_modification_log TO 'olympia_app'@'localhost';")
lines.append("GRANT SELECT ON olympia_auth.direct_modification_log TO 'olympia_app'@'localhost';\n")

lines.append("DELIMITER //\n")

for table, new_pk, old_pk in TABLES:
    for op, timing, pk_ref in OPS:
        trigger_name = f"{table}_direct_{op.lower()}"
        pk_expr = new_pk if pk_ref == "new_pk" else old_pk

        # Drop existing trigger first
        lines.append(f"DROP TRIGGER IF EXISTS olympia_track.{trigger_name}//\n")

        # The trigger:
        # 1. Inserts into direct_modification_log (dedicated tamper table)
        # 2. Inserts into audit_log with proper SHA-256 hash chain
        #    - Matches the exact canonical format from app/services/audit.py:
        #      timestamp|user_id|username|action|table_name|record_id|status|details|ip_address|prev_hash
        #    - timestamp format: YYYY-MM-DD HH:MM:SS.mmm (3-digit ms, matching Python's ms truncation)
        lines.append(f"""CREATE TRIGGER olympia_track.{trigger_name}
{timing} ON olympia_track.{table}
FOR EACH ROW
BEGIN
    DECLARE _prev_hash VARCHAR(64);
    DECLARE _ts VARCHAR(23);
    DECLARE _details TEXT;
    DECLARE _record_id VARCHAR(255);
    DECLARE _canonical TEXT;
    DECLARE _entry_hash VARCHAR(64);

    IF @api_context IS NULL OR @api_context != '{secret}' THEN
        SET _record_id = CAST({pk_expr} AS CHAR);
        SET _details = CONCAT('{{"source":"direct_db","db_user":"', CURRENT_USER(), '"}}');

        -- 1. Log to dedicated tamper table
        INSERT INTO olympia_auth.direct_modification_log
            (db_user, table_name, operation, row_key, details)
        VALUES (CURRENT_USER(), '{table}', '{op}', _record_id, '{op} detected without API context');

        -- 2. Log to main audit_log with hash chain
        SELECT entry_hash INTO _prev_hash
        FROM olympia_auth.audit_log ORDER BY log_id DESC LIMIT 1;
        IF _prev_hash IS NULL THEN
            SET _prev_hash = REPEAT('0', 64);
        END IF;

        SET _ts = LEFT(DATE_FORMAT(NOW(3), '%Y-%m-%d %H:%i:%s.%f'), 23);

        SET _canonical = CONCAT(
            _ts, '|',
            '', '|',
            'DIRECT_DB_ACCESS', '|',
            '{op}', '|',
            '{table}', '|',
            _record_id, '|',
            'UNAUTHORIZED', '|',
            _details, '|',
            '', '|',
            _prev_hash
        );
        SET _entry_hash = SHA2(_canonical, 256);

        INSERT INTO olympia_auth.audit_log
            (timestamp, user_id, username, action, table_name, record_id,
             status, details, ip_address, prev_hash, entry_hash)
        VALUES (NOW(3), NULL, 'DIRECT_DB_ACCESS', '{op}', '{table}', _record_id,
                'UNAUTHORIZED', _details, NULL, _prev_hash, _entry_hash);
    END IF;
END//
""")

lines.append("DELIMITER ;\n")

with open(out_path, "w") as f:
    f.write("\n".join(lines))

print(f"Generated {out_path} with {len(TABLES) * len(OPS)} triggers")
